# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: true
cache: packages
r:
  - release
addons:
  apt:
    packages:
      - jags
r_binary_packages:
   - rstan
   - Matrix
   - coda
   - testthat
   - rmarkdown
   - knitr
   - stringr
   - mvtnorm
r_build_args: --compact-vignettes="gs+qpdf"

env:
  - R_LIBS_SITE=/usr/lib/R/library

before_install:
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library

