# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: true
cache: packages
r:
  - release
addons:
  apt:
    packages:
      - jags
r_binary_packages:
   - Matrix
   - coda
   - testthat
   - rmarkdown
   - knitr
   - stringr
   - mvtnorm
r_build_args: --compact-vignettes="gs+qpdf"

